name: Honor Contributor

on:
  schedule:
    - cron: '35 7 * 10-3 *'  # Run this workflow at 8:30 AM Paris time (Standard Time)

jobs:
  honor-contributor:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-docker-image .

    - name: Run generateHonoredContribDataFile.sh
      run: docker run --rm -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} my-docker-image ./generateHonoredContribDataFile.sh
