name: Honor Contributor

on:
  schedule:
    - cron: '30 7 * 10-3 *'  # Run this workflow at 8:30 AM Paris time (Standard Time)
    - cron: '30 6 * 3-10 *'  # Run this workflow at 8:30 AM Paris time (Daylight Saving Time)

jobs:
  honor-contributor:
    runs-on: ubuntu-latest

    steps:
    - name: Check if current date is within Daylight Saving Time
      id: check-dst
      run: echo "::set-output name=is-dst::$(date +%-m | awk '{print $1 >= 3 && $1 <= 10 ? "true" : "false"}')"

    - name: Cancel workflow if current date is not within Daylight Saving Time
      if: ${{ github.event.schedule == '30 6 * 3-10 *' && steps.check-dst.outputs.is-dst == 'false' }}
      run: echo "Current date is not within Daylight Saving Time. Cancelling workflow." && exit 1

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-docker-image .

    - name: Run generateHonoredContribDataFile.sh
      run: docker run --rm -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} my-docker-image ./generateHonoredContribDataFile.sh
