# Honor Contributor Workflow
#
# This workflow is scheduled to run every day at 8 AM Paris time. It uses a Docker image to run a script that honors contributors.
#
# The workflow is triggered by the 'schedule' event, which is set to two cron schedules to account for Standard Time and Daylight Saving Time in Paris.
#
# The workflow contains a single job named 'honor-contributor', which runs on the latest version of Ubuntu.
#
# The 'honor-contributor' job consists of five steps:
# 1. 'Check if current date is within Daylight Saving Time': This step checks if the current month is between March and October (inclusive), which is the Daylight Saving Time period in Paris.
# 2. 'Cancel workflow if current date is not within Daylight Saving Time': This step cancels the workflow if the current date is not within the Daylight Saving Time period and the workflow was triggered by the Daylight Saving Time schedule.
# 3. 'Checkout code': This step uses the 'actions/checkout@v2' action to checkout the code from the current repository.
# 4. 'Build Docker image': This step builds a Docker image using the Dockerfile in the current repository. The resulting image is tagged as 'my-docker-image'.
# 5. 'Run generateHonoredContribDataFile.sh': This step runs the 'generateHonoredContribDataFile.sh' script inside a Docker container based on the 'my-docker-image' image.

name: Honor Contributor

on:
  schedule:
    - cron: '0 7 * 10-3 *'  # Run this workflow at 8 AM Paris time (Standard Time)
    - cron: '0 6 * 3-10 *'  # Run this workflow at 8 AM Paris time (Daylight Saving Time)

jobs:
  honor-contributor:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Check if current date is within Daylight Saving Time  # Check if the current month is between March and October (inclusive)
      id: check-dst
      run: echo "::set-output name=is-dst::$(date +%-m | awk '{print $1 >= 3 && $1 <= 10 ? "true" : "false"}')"

    - name: Cancel workflow if current date is not within Daylight Saving Time  # Cancel the workflow if the current date is not within the Daylight Saving Time period and the workflow was triggered by the Daylight Saving Time schedule
      if: ${{ github.event.schedule == '0 6 * 3-10 *' && steps.check-dst.outputs.is-dst == 'false' }}
      run: echo "Current date is not within Daylight Saving Time. Cancelling workflow." && exit 1

    - name: Checkout code  # Checkout the code from the current repository
      uses: actions/checkout@v2

    - name: Build Docker image  # Build a Docker image using the Dockerfile
      run: docker build -t my-docker-image .

    - name: Run generateHonoredContribDataFile.sh
      run: docker run --rm -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} my-docker-image ./generateHonoredContribDataFile.sh
